### ISSUE TITLE
Conda couldn't find a few packages when creating environment 

### ISSUE THREAD

**Issue by ykhli** [yael-vinker/SketchAgent#1]
Super excited to try this out. Although I'm running into this problem when doing conda env create locally. Curious if you happen to know what's the best way to resolve these dependencies? 

Thank you!!
```
 ~/code/SketchAgent git:(main) conda env create -f environment.yml
/opt/homebrew/anaconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - libnsl=2.0.1*
  - libgomp=14.2.0*
  - libgcc-ng=14.2.0*
  - libgcc=14.2.0*
  - ld_impl_linux-64=2.43*
  - _openmp_mutex=4.5*
  - _libgcc_mutex=0.1*

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by yael-vinker** [comment]
can you try removing these lines from the environment.yaml file and try to reinstall the env? let me know if it works

**Comment by yeeqie22** [comment]
@yael-vinker Hello, I'm excited to run the repo, but it seems that I have the same problem in my macbook(M1 chip,OSX-arm64),in what platform do you run the repo?

```
conda env create -f environment.yml                                           
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - libnsl=2.0.1*
  - libgomp=14.2.0*
  - libgcc-ng=14.2.0*
  - libgcc=14.2.0*
  - ld_impl_linux-64=2.43*
  - _openmp_mutex=4.5*
  - _libgcc_mutex=0.1*

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by yeeqie22** [comment]
> @yael-vinker Hello, I'm excited to run the repo, but it seems that I have the same problem in my macbook(M1 chip,OSX-arm64),in what platform do you run the repo?
> 
> Much Thanks!
> 
> ```
> conda env create -f environment.yml                                           
> Channels:
>  - conda-forge
>  - defaults
> Platform: osx-arm64
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - libnsl=2.0.1*
>   - libgomp=14.2.0*
>   - libgcc-ng=14.2.0*
>   - libgcc=14.2.0*
>   - ld_impl_linux-64=2.43*
>   - _openmp_mutex=4.5*
>   - _libgcc_mutex=0.1*
> 
> Current channels:
> 
>   - https://conda.anaconda.org/conda-forge
>   - https://repo.anaconda.com/pkgs/main
>   - https://repo.anaconda.com/pkgs/r
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> ```

--------------------------------------------------------------------------------------------------------
afterwords: Just delete the pakage and the err get fixed!!!
